# Generated by Django 5.0.2 on 2024-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('breed', models.CharField(choices=[('pe', 'Persa'), ('si', 'Siamês'), ('ab', 'Abissínio'), ('mc', 'Maine Coon'), ('sf', 'Esfinge'), ('rg', 'Ragdoll'), ('bn', 'Bengal'), ('br', 'Birmanês'), ('dr', 'Devon Rex')], max_length=2)),
                ('color', models.CharField(choices=[('pr', 'Preto'), ('br', 'Branco'), ('ci', 'Cinza'), ('ma', 'Malhado'), ('ta', 'Tabby'), ('ca', 'Carey')], max_length=2)),
            ],
        ),
    ]
